# Common Data Types

## Strings 
### A sequence of characters definedd by either single or double quotes

In [1]:
'Hello World'

'Hello World'

In [2]:
'Hello World'. upper()

'HELLO WORLD'

In [3]:
'Hello World' . lower()

'hello world'

In [4]:
'Hello World' . capitalize()

'Hello world'

In [5]:
'Hello World' * 2

'Hello WorldHello World'

In [6]:
'Hello' + 'Wolrd'

'HelloWolrd'

## Intergers
### Whole numbers eg 5
## Floats
### Decimals eg 1.2

In [7]:
int ('1')

1

In [8]:
int (1.1)

1

In [9]:
float ('1.1')

1.1

In [10]:
float (1)

1.0

In [11]:
7/3 #Python will convert an interger to a float when performing maths operations

2.3333333333333335

## Lists
### Changeable collection of ordered items
### Use for a collection that will change

In [34]:
[1,2,3,34]

[1, 2, 3, 34]

In [35]:
['Alice', 'John']

['Alice', 'John']

In [36]:
numbers=[1,2,3,4]

In [37]:
fruits=['apples','banana', 'cherry']

In [38]:
mixed=[1, 'apple', True]

### Accessing the elements

In [39]:
print(numbers[0]) #prints the first element

1


In [40]:
print(fruits[2]) #prints the third element

cherry


##### Negative indexing

In [41]:
print(fruits[-1]) #prints the last element

cherry


In [42]:
print(fruits[-2]) #prints the second last element

banana


##### Modifying lists

In [77]:
fruits=['apples','banana', 'cherry']

In [78]:
print(fruits)

['apples', 'banana', 'cherry']


In [79]:
 fruits. append('orange')#adds orange as the last element in the list

In [80]:
print(fruits)

['apples', 'banana', 'cherry', 'orange']


In [81]:
fruits.insert(1, 'watermelon') # adds watermelon as the second element in the list

In [82]:
print(fruits)

['apples', 'watermelon', 'banana', 'cherry', 'orange']


In [83]:
fruits.remove('orange') 

In [84]:
print(fruits)

['apples', 'watermelon', 'banana', 'cherry']


In [85]:
fruits.remove('watermelon') 

In [86]:
print(fruits)

['apples', 'banana', 'cherry']


If you run the codes 'remove' and 'append' more than once, the outcome repeats itself, ie if you run the code with append twice, the outcome will have the element added twice.

In [93]:
fruits=['apples','banana', 'cherry']

In [94]:
del fruits[0] #removes the first element in the list fruits

In [95]:
print(fruits)

['banana', 'cherry']


In [96]:
fruits.pop() #removes the last element in the list

'cherry'

In [97]:
print(fruits)

['banana']


In [98]:
fruits=['apples','banana', 'cherry']

In [99]:
fruits.pop()

'cherry'

In [100]:
print(fruits)

['apples', 'banana']


##### Slicing lists

In [101]:
fruits=['apples','banana', 'cherry','watermelon']

In [102]:
sliced_fruits = fruits[1:3] #prints the second element not including the third
print(sliced_fruits)

['banana', 'cherry']


In [103]:
sliced_fruits = fruits[1:4] #prints the second element not including the third
print(sliced_fruits)

['banana', 'cherry', 'watermelon']


## Tuples
### Unchangeable collection of ordered items
### Cannot be changed
### Use for fixed data eg coordinates, days of the weeks, data base records 

#### Creating tuples

In [104]:
colors=('red','green', 'blue') #three item tuple

In [106]:
single_item=('glass',) #use a comma at the end to write a single item tuple

#### Accessing elements

In [107]:
colors=('red','green', 'blue') #prints the first element in a tuple
print(colors[0])

red


In [108]:
print(colors[-1])

blue


## Dictionaries
### These are key value pairs.

#### Creating a dictionary

In [110]:
student ={'name':'Alice', 'age':25, 'grade': 'A'} #gives you the student name
print(student['age'])

25


#### Adding and Updating a dictionary

In [114]:
student ={'name':'Alice', 'age':25, 'grade': 'A'} 
student['subject']='Maths' #Adds a key and a value
student['age']=32 #Updates the age 
print(student)

{'name': 'Alice', 'age': 32, 'grade': 'A', 'subject': 'Maths'}


#### Removing

In [115]:
student ={'name':'Alice', 'age':25, 'grade': 'A'} #gives you the student name
print(student)

{'name': 'Alice', 'age': 25, 'grade': 'A'}


In [118]:
del student['grade']
print (student)

{'name': 'Alice', 'age': 25}


In [125]:
student.pop('name', None) #removes the key student
print (student) 

{'age': 25}


In [128]:
student ={'name':'Alice', 'age':25, 'grade': 'A'} #gives you the student name
print(student)

{'name': 'Alice', 'age': 25, 'grade': 'A'}


In [129]:
student['gender']='Female'
print(student)

{'name': 'Alice', 'age': 25, 'grade': 'A', 'gender': 'Female'}


In [132]:
student.pop('age', None)  #removes the key age
print(student) 

{'name': 'Alice', 'grade': 'A', 'gender': 'Female'}


#### Iteration

In [134]:
student ={'name':'Alice', 'age':25, 'grade': 'A'}
student['gender']='Female'
print(student)

{'name': 'Alice', 'age': 25, 'grade': 'A', 'gender': 'Female'}


In [135]:
for key, value in student.items():
    print(key,value)

name Alice
age 25
grade A
gender Female


### Creating a dictionary of the show friends

In [5]:
friends={'name':'Friends', 'genre':'sitcom', 'no_of_episodes':10}
print(friends['genre'])

sitcom


In [8]:
help(dict) #see all methods available for dictionary objects

Help on class dict in module builtins:

class dict(object)
 |  dict() -> new empty dictionary
 |  dict(mapping) -> new dictionary initialized from a mapping object's
 |      (key, value) pairs
 |  dict(iterable) -> new dictionary initialized as if via:
 |      d = {}
 |      for k, v in iterable:
 |          d[k] = v
 |  dict(**kwargs) -> new dictionary initialized with the name=value pairs
 |      in the keyword argument list.  For example:  dict(one=1, two=2)
 |
 |  Built-in subclasses:
 |      StgDict
 |
 |  Methods defined here:
 |
 |  __contains__(self, key, /)
 |      True if the dictionary has the specified key, else False.
 |
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(self, key, /)
 |      Return self[key].
 |
 |  __gt__(self, value, /)
 |      Return self>va

In [9]:
friends.get #Add a dot (.) after 'friends' and press tab to see all of the available methods
friends

<function dict.get(key, default=None, /)>

In [10]:
friends.get? #Pulling up documentation for a specific method
friends.get?

Signature: friends.get(key, default=None, /)
Docstring: Return the value for key if key is in the dictionary, else default.
Type:      builtin_function_or_method

In [12]:
friends={'name':'Friends', 'genre':'Sitcom', 'no_of_seasons':10,'creators':['David Crane','Marta Kauffman']}
print(friends['creators'])

['David Crane', 'Marta Kauffman']


In [14]:
first_creator = friends['creators'][0]
print(first_creator)

David Crane


In [15]:
second_creator = friends['creators'][1]
print(second_creator)

Marta Kauffman


In [18]:
seinfeld={'name':'Seinfeld','genre':'Sitcom', 'creators':['Larry David','Jerry Seinfeld'], 'no_of_seasons':9, 'no_of_episodes':180}
print(seinfeld['name'])

Seinfeld


In [21]:
tv_shows = [friends, seinfeld]
tv_shows

[{'name': 'Friends',
  'genre': 'Sitcom',
  'no_of_seasons': 10,
  'creators': ['David Crane', 'Marta Kauffman']},
 {'name': 'Seinfeld',
  'genre': 'Sitcom',
  'creators': ['Larry David', 'Jerry Seinfeld'],
  'no_of_seasons': 9,
  'no_of_episodes': 180}]

In [22]:
tv_shows[1]

{'name': 'Seinfeld',
 'genre': 'Sitcom',
 'creators': ['Larry David', 'Jerry Seinfeld'],
 'no_of_seasons': 9,
 'no_of_episodes': 180}

In [23]:
tv_shows[0]

{'name': 'Friends',
 'genre': 'Sitcom',
 'no_of_seasons': 10,
 'creators': ['David Crane', 'Marta Kauffman']}

In [26]:
tv_shows[1]['creators']

['Larry David', 'Jerry Seinfeld']

In [27]:
tv_shows[1]['creators'][1]

'Jerry Seinfeld'

In [28]:
greenville = {'Area': 68, 'City': 'Greenville', 'Country': 'USA', 'Population': 84554}
#Here is a dictionary representing the city of Greenville, North Carolina. The area is in kilometers squared.

In [30]:
greenville={'Area':68, 'City': 'Greenville', 'Country': 'USA', 'Population':84554}
print(greenville['Population'])
#retrieving the population of the city

84554


In [58]:
greenville={'Area':68, 'City': 'Greenville', 'Country': 'USA', 'Population':84554}
print(greenville['Population'])

84554


In [33]:
greenville_population=greenville['Population']
print(greenville_population)

84554


In [35]:
greenville_area=greenville['Area']
print(greenville_area)
#Retrieving area

68


In [36]:
city_keys = ['Area', 'City', 'Greenville', 'Country', 'Population']
print(city_keys)

['Area', 'City', 'Greenville', 'Country', 'Population']


In [37]:
city_values=[68, 'Greenville', 'USA',84554]
print(city_values)

[68, 'Greenville', 'USA', 84554]


In [49]:
!pip install openpyxl



[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [50]:
import pandas as pd
df = pd.read_excel(r'C:\Users\Lenovo\Downloads\cities.xlsx')
print(df.head())



                 City    Country  Population  Area
0               Solta    Croatia        1700    59
1          Greenville        USA       84554    68
2        Buenos Aires  Argentina    13591863  4758
3           Los Cabos     Mexico      287651  3750
4  Walla Walla Valley        USA       32237    33


In [54]:
cities=[{'City': 'Solta', 'Country': 'Croatia', 'Population': 1700, 'Area': 59},
 {'City': 'Greenville', 'Country': 'USA', 'Population': 84554, 'Area': 68},
 {'City': 'Buenos Aires',
  'Country': 'Argentina',
  'Population': 13591863,
  'Area': 4758},
 {'City': 'Los Cabos',
  'Country': 'Mexico',
  'Population': 287651,
  'Area': 3750},
 {'City': 'Walla Walla Valley',
  'Country': 'USA',
  'Population': 32237,
  'Area': 33},
 {'City': 'Marakesh', 'Country': 'Morocco', 'Population': 928850, 'Area': 200},
 {'City': 'Albuquerque',
  'Country': 'New Mexico',
  'Population': 559277,
  'Area': 491},
 {'City': 'Archipelago Sea',
  'Country': 'Finland',
  'Population': 60000,
  'Area': 8300},
 {'City': 'Iguazu Falls',
  'Country': 'Argentina',
  'Population': 0,
  'Area': 672},
 {'City': 'Salina Island', 'Country': 'Italy', 'Population': 4000, 'Area': 27},
 {'City': 'Toronto', 'Country': 'Canada', 'Population': 630, 'Area': 2731571},
 {'City': 'Pyeongchang',
  'Country': 'South Korea',
  'Population': 2581000,
  'Area': 3194}]

#### First, access the third to last element and set it equal to the variable salina.

In [61]:
salina = cities[-3]
print(salina)


{'City': 'Salina Island', 'Country': 'Italy', 'Population': 4000, 'Area': 27}


#### Now access the fourth city in the list, and set its population equal to a variable called los_cabos_pop.

In [62]:
los_cabos_pop=cities[4]['Population']
print(los_cabos_pop)

32237


#### Now calculate the number of cities in the list and assign the number to the variable city_count

In [63]:
city_count=len(cities)
print(city_count)

12


#### Finally, change the spelling of the South Korean city, Pyeongchang, to the string 'PyeongChang', its alternative spelling.

In [64]:
cities[11]['City'] = 'PyeongChang'
print(cities[11])


{'City': 'PyeongChang', 'Country': 'South Korea', 'Population': 2581000, 'Area': 3194}


#### Now let's work on retrieving a collection of information about a dictionary. Use the appropriate dictionary method to return a list of values in the dictionary regarding Pyeongchang. Assign the list to the variable pyeongchang_values.

In [65]:
pyeongchang_values = list(cities[11].values())
print(pyeongchang_values)


['PyeongChang', 'South Korea', 2581000, 3194]


####  now set pyeongchang_keys equal to a list of keys in the dictionary regarding Pyeongchang.

In [66]:
pyeongchang_keys = list(cities[11].keys())
print(pyeongchang_keys)


['City', 'Country', 'Population', 'Area']


## Sets

In [2]:
numbers={1,2,3,4} #Creating sets

#### Adding and removing sets

In [3]:
numbers = {1,2,3,4}
numbers.add(5) #adds a new number to the set
print(numbers)

{1, 2, 3, 4, 5}


In [4]:
numbers.remove(2)
print(numbers)

{1, 3, 4, 5}


#### Set Operations

Union

In [5]:
set1={1,2,3}
set2={3,4,5}
print(set1|set2)

{1, 2, 3, 4, 5}


## Booleans- true or false 

## Udemy exercise- day 1

### Practice writing and manipulating variables of different data types

In [82]:
integer_var=10
float_var=3.14
string_var='AI'
list_var=[1,2,3]
tuple_var=(4,5,6)
dict_var={'name':'Alice', 'role':'Engineer'}
boolean_var=True

In [83]:
print('integer:', integer_var)

integer: 10


In [84]:
print('float:', float_var)

float: 3.14


In [85]:
print('string:', string_var + 'bootcamp')

string: AIbootcamp


In [86]:
list_var.append(4)
print('list:',list_var)

list: [1, 2, 3, 4]


In [81]:
print('tuple:', tuple_var)

tuple: (4, 5, 6)


In [87]:
print('dictionary:', dict_var['name'])

dictionary: Alice


In [88]:
print('boolean:',boolean_var)

boolean: True


## Control flow in Python

### Conditionals allow you to make decisions based on conditions(true or false)
#### if-executes code if a codition is true
#### elseif-adds additional conditions after the initial if
#### else- executes code if none of the previous conditions are  met

### Checking a condition

In [94]:
num = 10
if num > 0:
    print('Positive Number')
elif num == 0:
    print('Zero')
else:
    print('Negative Number')

    

Positive Number


## Nested conditions
### Conditional statements placed inside other conditional statements

In [95]:
age=25
if age>18:
    if age<30:
        print('Young Adult')
    else:
        print('Adult')

Young Adult


In [96]:
age=41
if age>18:
    if age<30:
        print('Young Adult')
    else:
        print('Adult')

Adult


In [98]:
age=5
if age>18:
    if age<30:
        print('Young Adult')
    else:
        print('Adult')

number_50 = 50
my_number = None
if number_50 > 100:
    # if number_50 is greater than 100, assign the `my_number` variable to the number 100
elif number_50 > 50:
    # if number_50 is greater than 50, assign the `my_number` variable to the number 50
else:
    # else assign the `my_number` variable to 0

In [104]:
number_50=50
my_number=None
if number_50>100:
    my_number=100
elif number_50>50:
    my_number=50
else:
    my_number=0
print (my_number)


0


Below, use conditionals to tell whether it is hot outside or not. If it is hot, assign the string "It is so hot out!" to the variable is_it_hot. If it is not hot, assign the string "This is nothing! Bring on the heat.". For our purposes, anything over 80 degrees is considered hot.

In [106]:
temperature = 85
is_it_hot = None
if temperature>85:
    is_it_hot='It is so hot out!'
else:
    is_it_hot='This is nothing!Bring on the heat.'
print (is_it_hot)

This is nothing!Bring on the heat.


Next, let's see what day of the week it is. There are 7 days in the week starting with Sunday at day 1 and ending with Saturday at day 7. Use conditional statements to assign the day of the week to the variable day_of_the_week based on the number below assigned to the variable today_is. For example, if the day is 2, we would assign day_of_the_week the value "Monday".

In [109]:
today_is = 4
day_of_the_week = None
if today_is == 1:
    day_of_the_week= 'Sunday'
elif today_is == 2:
    day_of_the_week = 'Monday'
elif today_is == 3:
    day_of_the_week = 'Tuesday'
elif today_is == 4:
    day_of_the_week = 'Wednesday'
elif today_is == 5:
    day_of_the_week = 'Thursday'
elif today_is == 6:
    day_of_the_week = 'Friday'
elif today_is == 7:
    day_of_the_week = 'Saturday'
print (day_of_the_week)


Wednesday


## Loops

### for loops- allow you to iterate over elements in a collection, eg lists, tuples, dictionaries, set etc

In [2]:
#loop through a list of fruits
fruits= ['apple','banana','cherry']
for fruit in fruits:
    print(fruit)

apple
banana
cherry


In [3]:
#loop through a range
for i in range(5):
    print (i)

0
1
2
3
4


In [1]:
for i in range (10,15):
    print (i)

10
11
12
13
14


In [2]:
#increament of the sequence with 3
for i in range (2,30,3):
    print (i)

2
5
8
11
14
17
20
23
26
29


In [2]:
#looping through a string
for x in 'banana': 
    print(x)

b
a
n
a
n
a


### while loop- executes so long as the condition is true.

In [3]:
count = 5
while count >0:
    print (count)
    count -=1


5
4
3
2
1


In [10]:
i = 0
while i < 6:
    print(i)
    i += 1


0
1
2
3
4
5


### Break and continue

In [4]:
for i in range (10):
    if i ==5:
        break
    print (i)

0
1
2
3
4


In [5]:
for i in range (10):
    if i == 7:
        continue
    print  (i)

0
1
2
3
4
5
6
8
9


In [6]:
# print only odd numbers in the range of 10
for i in range (10):
    if i % 2 ==0:
        continue
    print (i)

1
3
5
7
9


In [2]:
# check if a number is a prime number
num = int(input("Enter a number: "))

if num < 2:
    print(f"{num} is not a prime number.")
else:
    is_prime = True
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            is_prime = False
            break

    if is_prime:
        print(f"{num} is a prime number.")
    else:
        print(f"{num} is not a prime number.")


Enter a number:  87


87 is not a prime number.


In [3]:
# create a menu driven calculator
# write a program to calculate the factorial of a number using a while loop

## Functions and Modules

In [4]:
#create a function with parameters and return values
def add_numbers(a,b):
    return (a+b)
result= add_numbers(45,3)
print ('sum:', result)


sum: 48


In [10]:
travel_destinations = ['argentina', 'mexico', 'italy', 'finland', 'canada', 'croatia']
def number_of_destinations():
    return len(travel_destinations)
print ('Number of destinations:', number_of_destinations())

Number of destinations: 6


In [12]:
travel_destinations = ['argentina', 'mexico', 'italy', 'finland', 'canada', 'croatia']
def next_up():
    return travel_destinations[0]
print ('Next up:',next_up())

Next up: argentina


In [14]:
list_of_destinations = ['argentina', 'canada', 'croatia']
def next_up():
    return list_of_destinations[0]
print ('Next up:',next_up())

Next up: argentina


Ok, now write a function called favorite_destination() that returns the string 'madagascar'.

In [24]:
list_of_destinations = ['argentina', 'canada', 'croatia']
def favorite_destination():
    list_of_destinations.append('madagascar')
    return 'madagascar'
print ('Favorite Destination:',favorite_destination())

Favorite Destination: madagascar


In [25]:
capitalized_destinations = ['argentina', 'canada', 'croatia', 'madagascar']
def capitalize_countries():
    capitalized_list = []
    for country in capitalized_destinations:
        capitalized_list.append(country.capitalize())
    return capitalized_list
print("Capitalized Destinations:", capitalize_countries())


Capitalized Destinations: ['Argentina', 'Canada', 'Croatia', 'Madagascar']


## Reading and writing text files

#### Opening files

##### Reading an entire file

##### Reading line by line

##### Appending to a file

### Pythonic code

## Introduction to Numpy

### Creating arrays

In [5]:
import numpy as np

In [8]:
#creating an array from a list
arr = np.array([1,2,3,4])
print (arr)

[1 2 3 4]


In [9]:
#creating from an in-built function
zeroes= np.zeros ((3,3))
print(zeroes)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
ones=np.ones ((2,4)) #print ones in a matrix of 2R by 4C
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
range_array=np.arange(1,10,2) #prints the numbers 1 to 10 while skipping 1
print (range_array)

[1 3 5 7 9]


In [13]:
range_array=np.arange(1,10,3) #prints the numbers 1 to 10 while skipping 1
print (range_array)

[1 4 7]


In [14]:
linspace_array=np.linspace(0, 1, 5) #prints 5 evenly spaced numbers from 0 to 1
print (linspace_array)

[0.   0.25 0.5  0.75 1.  ]


In [15]:
linspace_array=np.linspace(0, 6, 4) #prints 4 evenly spaced numbers from 0 to 6
print (linspace_array)

[0. 2. 4. 6.]


### Manipulating arrays

In [20]:
arr =np.array([1,2,3,4,5,6]) #reshapes the array into 2 row and 3 column matrix
reshaped= arr.reshape ((2,3))
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [27]:
arr =np.array([1,2,3,4,5,6]) #reshapes the array into 6 row and 1 column matrix
reshaped= arr.reshape ((6,1))
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [74]:
random_array = np.random.randint(1,7, size=(2,3)) #generating a random matrix with integer values ranging from 1 but not including 7 to form a 2 by 3 matrix
print (random_array)

[[1 1 2]
 [5 5 5]]


In [75]:
random_array = np.random.randint(1,7, size=(2,3))
print (random_array)

[[5 5 4]
 [1 6 6]]


In [29]:
arr=np.array ([1,2,3])
expanded= arr[:,np.newaxis]
print (expanded)

[[1]
 [2]
 [3]]


## Basic Operations on Arrays

In [34]:
a=np.array ([1,2,3])
b=np.array ([4,5,6])
print (a+b) #adds the elemts of the list of arrays

[5 7 9]


In [35]:
a=np.array ([1,2,3])
b=np.array ([4,5,6])
print (a*b) #multiplies the elemts of the list of arrays

[ 4 10 18]


In [37]:
a=np.array ([1,2,3])
b=np.array ([4,5,6])
print (a/b)

[0.25 0.4  0.5 ]


In [39]:
arr=np.array ([4,16,25])
print (np.sqrt(arr)) #prints the sqrt of the elements of the array

[2. 4. 5.]


In [40]:
arr=np.array ([4,16,25])
print (np.sum(arr)) #prints the sum of the elements

45


In [41]:
arr=np.array ([4,16,25])
print (np.mean(arr)) #prints the mean of the elements

15.0


In [42]:
arr=np.array ([4,16,25])
print (np.max(arr)) #prints the highest number of the elements

25


In [43]:
arr=np.array ([4,16,25])
print (np.min(arr)) #prints the lowest number of the elements

4


### Array indexing, slicing and reshaping

In [44]:
arr=np.array([10,20,30,40,50])
print(arr[2]) #prints the second item in the list of arrays

30


In [45]:
arr=np.array([10,20,30,40,50])
print(arr[-1]) #prints the last item in the list of arrays

50


In [47]:
arr=np.array([10,20,30,40,50])
print(arr[1:4]) #prints the first to fourth element

[20 30 40]


In [48]:
arr=np.array([10,20,30,40,50])
print(arr[:3]) #prints upto the 2nd element

[10 20 30]


In [49]:
arr=np.array([10,20,30,40,50])
print(arr[0:3])#prints upto the 2nd element

[10 20 30]


In [50]:
arr=np.array([10,20,30,40,50])
print(arr[3:]) #prints the 3rd index to the last

[40 50]


In [51]:
arr=np.array([10,20,30,40,50,60])
reshaped= arr.reshape(2,3)
print (reshaped)

[[10 20 30]
 [40 50 60]]


In [52]:
arr=np.array([10,20,30,40,50,60])
reshaped= arr.reshape(3,2)
print (reshaped)

[[10 20]
 [30 40]
 [50 60]]


In [54]:
arr=np.array([10,20,30,40,50,60])
reshaped= arr.reshape(6,1)
print (reshaped)

[[10]
 [20]
 [30]
 [40]
 [50]
 [60]]


#### Generate arrays for basic mathematical operations

In [61]:
a=np.arange(1,6)
b=np.arange(6,11)
print (a+b)
print (a*b)
print (a/b)
print(b-a)

[ 7  9 11 13 15]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[5 5 5 5 5]


#### Create a 3x3 matrix and perform operartions

In [62]:
# Define a 3x3 matrix
matrix = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Transpose the matrix
transposed_matrix = matrix.T

# Print original and transposed
print("Original Matrix:")
print(matrix)

print("\nTransposed Matrix:")
print(transposed_matrix)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transposed Matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [65]:
another_matrix =np.array([[3,4,5],[6,7,8],[2,7,9]])

print (matrix+another_matrix)
print (matrix*another_matrix)

[[ 4  6  8]
 [10 12 14]
 [ 9 15 18]]
[[ 3  8 15]
 [24 35 48]
 [14 56 81]]


#### Create a 4 by 4 matrix and calculate the sum and mean of its rows and columns

In [69]:
matr1=np.array([[1,2,3,4],
                [5,6,7,8],
                [3,4,5,6],
                [2,3,4,5]])
sum_row=np.sum(matr1,axis=1)  #axis=1 means sum across rows
print (sum_row)
sum_col=np.sum(matr1,axis=0)  #axis=0 means sum down rows
print(sum_col)
mean_row=np.mean (matr1, axis=1)
print (mean_row)

[10 26 18 14]
[11 15 19 23]
[2.5 6.5 4.5 3.5]


#### Generate a random array and find the minimum and maximum values

In [111]:

# Generate a random 2D array (e.g. 4x4) with values from 0 to 100
random_array = np.random.randint(0, 101, size=(4, 4))

print("Random Array:\n")
print(random_array)

# Find the minimum and maximum values
min_value = np.min(random_array)
max_value = np.max(random_array)

print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)


Random Array:

[[75 65 62 48]
 [44 75 22 34]
 [ 3 80 87 60]
 [70 66 76 52]]

Minimum Value: 3
Maximum Value: 87


#### Write a program to normalize an array (scale values between 0 and 1)

In [87]:
random_arr1=np.random.randint(1,51, size=(4,4))
print('random_arr1:')
print (random_arr1)
min_value = np.min(random_arr1)
print ('\nMinumum Value:', min_value)
max_value = np.max(random_arr1)
print('Maximum Value:', max_value)
normalized_array= (random_arr1-min_value)/(max_value-min_value) #formula for normalizing data/ scaling the data to a range between 0n and 1
print (normalized_array)

random_arr1:
[[46 39  4 28]
 [26 39 23  4]
 [48 12 38 37]
 [29 23 30 17]]

Minumum Value: 4
Maximum Value: 48
[[0.95454545 0.79545455 0.         0.54545455]
 [0.5        0.79545455 0.43181818 0.        ]
 [1.         0.18181818 0.77272727 0.75      ]
 [0.56818182 0.43181818 0.59090909 0.29545455]]


### Broadcasting in Numpy

#### Array and scalar broadcasting

In [99]:
arr=np.array([2,4,6])
print (arr+10)
print (arr-1)
print(arr*2)
print (arr/2)
print(arr**5)


[12 14 16]
[1 3 5]
[ 4  8 12]
[1. 2. 3.]
[  32 1024 7776]


In [103]:
matrix=np.array([[5,6,7],[3,5,6]])
vector=np.array([1,2,4])
print (matrix+vector)
print (matrix*vector)
print (matrix-vector)

[[ 6  8 11]
 [ 4  7 10]]
[[ 5 12 28]
 [ 3 10 24]]
[[4 4 3]
 [2 3 2]]


#### Aggregation Functions

In [109]:
arr= np.array ([[2,3,4],[5,6,7]])
print ("Sum:", np.sum(arr))
print ("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min",np.min(arr))
print ("Standard Deviation", np.std(arr))
print("Sum along rows", np.sum(arr, axis=1))
print("Sum down rows", np.sum(arr, axis=0))

Sum: 27
Mean: 4.5
Max: 7
Min 2
Standard Deviation 1.707825127659933
Sum along rows [ 9 18]
Sum down rows [ 7  9 11]


### Boolean Indexing and filtering

In [3]:
import numpy as np

In [4]:
arr= np.array([1,2,3,4,5,6]) #prints an array of even numbers
even_numbers=arr[arr%2==0]
print ("Even Numbers", even_numbers)

Even Numbers [2 4 6]


In [5]:
arr = np.array([1,2,3,4,5,6]) #prints an array of odd numbers
odd_numbers= arr[arr%2==1]
print ("Odd numbers", odd_numbers)

Odd numbers [1 3 5]


In [6]:
arr[arr>3]=0 #prints numbers that are greater than 3 to 0s
print ("Modified array", arr)

Modified array [1 2 3 0 0 0]


In [7]:
random_arr1=np.random.rand(3,3) #prints a random array
print('Random Array: \n' , random_arr1)

Random Array: 
 [[0.51133058 0.81673225 0.77255464]
 [0.31252498 0.09184064 0.78056499]
 [0.58719963 0.60399931 0.72864638]]


In [8]:
np.random.seed(8) #this command returns the same numbers every time you run it
random_arr2=np.random.randint(2,60, size=(3,2))
print ("Random Array: \n", random_arr2)

Random Array: 
 [[ 5 22]
 [51 43]
 [ 7 28]]


In [9]:
dataset=np.random.randint(1,51, size=(5,5))
print ("Original Dataset: \n", dataset)
dataset[dataset>25]=0
print("Filtered array: \n", dataset)

Original Dataset: 
 [[ 9 20 41 49 46]
 [22 50 11 28 45]
 [14 10 16 30 35]
 [19 15 39 30 10]
 [ 5  8 43 42 27]]
Filtered array: 
 [[ 9 20  0  0  0]
 [22  0 11  0  0]
 [14 10 16  0  0]
 [19 15  0  0 10]
 [ 5  8  0  0  0]]


In [10]:
random_dataset=np.random.rand(4,4)
print ("Original Dataset : \n", random_dataset)
max_value=np.max(random_dataset)
print(f"Maximum value: {max_value} ")
min_value=np.min(random_dataset)
print("Minimum value: ", min_value)
normalized_dataset= (random_dataset-min_value)/(max_value-min_value)
print ("Normalized Value: \n", normalized_dataset)

Original Dataset : 
 [[0.29214247 0.67652011 0.30061802 0.1827028 ]
 [0.4402284  0.53098972 0.94520391 0.51362777]
 [0.67357127 0.1217076  0.33263827 0.27445472]
 [0.57034489 0.66012071 0.28208075 0.14658688]]
Maximum value: 0.9452039144646004 
Minimum value:  0.12170760354945098
Normalized Value: 
 [[0.20696495 0.67372798 0.21725709 0.07406857]
 [0.3867908  0.49700541 1.         0.47592219]
 [0.67014711 0.         0.25614039 0.1854861 ]
 [0.54479574 0.65381362 0.19474665 0.03021177]]


In [11]:
arr=np.array([1,5,2,8,3,7])
mask= arr>4
print (mask)
binary_mask = (arr>4).astype(int)
print (binary_mask)


[False  True False  True False  True]
[0 1 0 1 0 1]


In [12]:
arr=np.array([1,5,2,8,3,7])
mask= arr<6
print (mask)
binary_mask = (arr<6).astype(int)
print (binary_mask)

[ True  True  True False  True False]
[1 1 1 0 1 0]


## Introduction to pandas for data manipulation

In [13]:
import pandas as pd
import numpy as np

In [14]:
df=pd.read_csv("iris.csv") #importing the dataset
print (df)
print (df.head(10)) #displays the first 5 entries of the dataset
print(df.tail()) #displays the last 5 entries of the data set
print(df.info()) #gives summary of the dataset
print(df.describe()) #summary statistics of the dataset

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]
   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9     

In [15]:
selected_columns=df[["sepal.length","variety"]]
print("Selected Columns: \n", selected_columns)

Selected Columns: 
      sepal.length    variety
0             5.1     Setosa
1             4.9     Setosa
2             4.7     Setosa
3             4.6     Setosa
4             5.0     Setosa
..            ...        ...
145           6.7  Virginica
146           6.3  Virginica
147           6.5  Virginica
148           6.2  Virginica
149           5.9  Virginica

[150 rows x 2 columns]


In [17]:
filtered_rows = df[(df["sepal.length"] > 2.0) & (df["variety"] == "Setosa")]
print("Filtered Rows:\n", filtered_rows)

Filtered Rows:
     sepal.length  sepal.width  petal.length  petal.width variety
0            5.1          3.5           1.4          0.2  Setosa
1            4.9          3.0           1.4          0.2  Setosa
2            4.7          3.2           1.3          0.2  Setosa
3            4.6          3.1           1.5          0.2  Setosa
4            5.0          3.6           1.4          0.2  Setosa
5            5.4          3.9           1.7          0.4  Setosa
6            4.6          3.4           1.4          0.3  Setosa
7            5.0          3.4           1.5          0.2  Setosa
8            4.4          2.9           1.4          0.2  Setosa
9            4.9          3.1           1.5          0.1  Setosa
10           5.4          3.7           1.5          0.2  Setosa
11           4.8          3.4           1.6          0.2  Setosa
12           4.8          3.0           1.4          0.1  Setosa
13           4.3          3.0           1.1          0.1  Setosa
14       

In [20]:
filtered_rows.to_csv("filtered_setosa.csv", index=False) #saving filtered data to a new csv

In [31]:
df=pd.read_csv("titanic_dataset.csv") #loading the dataset
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ... 

In [46]:
df.head(20)

PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
12           13         0       3   
13           14         0       3   
14           15         0       3   
15           16         1       2   
16           17         0       3   
17           18         1       2   
18           19         0       3   
19           20         1       3   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss. Laina  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
5                                    Moran, Mr. James    male   NaN      0   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
7                      Palsson, Master. Gosta Leonard    male   2.0      3   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
12                     Saundercock, Mr. William Henry    male  20.0      0   
13                        Andersson, Mr. Anders Johan    male  39.0      1   
14               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                               Rice, Master. Eugene    male   2.0      4   
17                       Williams, Mr. Charles Eugene    male   NaN      0   
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                            Masselmani, Mrs. Fatima  female   NaN      0   

    Parch            Ticket     Fare Cabin Embarked  
0       0         A/5 21171   7.2500   NaN        S  
1       0          PC 17599  71.2833   C85        C  
2       0  STON/O2. 3101282   7.9250   NaN        S  
3       0            113803  53.1000  C123        S  
4       0            373450   8.0500   NaN        S  
5       0            330877   8.4583   NaN        Q  
6       0             17463  51.8625   E46        S  
7       1            349909  21.0750   NaN        S  
8       2            347742  11.1333   NaN        S  
9       0            237736  30.0708   NaN        C  
10      1           PP 9549  16.7000    G6        S  
11      0            113783  26.5500  C103        S  
12      0         A/5. 2151   8.0500   NaN        S  
13      5            347082  31.2750   NaN        S  
14      0            350406   7.8542   NaN        S  
15      0            248706  16.0000   NaN        S  
16      1            382652  29.1250   NaN        Q  
17      0            244373  13.0000   NaN        S  
18      0            345763  18.0000   NaN        S  
19      0              2649   7.2250   NaN        C

In [37]:
df.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [38]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [39]:
df.isna()

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False   
1          False     False   False  False  False  False  False  False   False   
2          False     False   False  False  False  False  False  False   False   
3          False     False   False  False  False  False  False  False   False   
4          False     False   False  False  False  False  False  False   False   
..           ...       ...     ...    ...    ...    ...    ...    ...     ...   
886        False     False   False  False  False  False  False  False   False   
887        False     False   False  False  False  False  False  False   False   
888        False     False   False  False  False   True  False  False   False   
889        False     False   False  False  False  False  False  False   False   
890        False     False   False  False  False  False  False  False   False   

      Fare  Cabin  Embarked  
0    False   True     False  
1    False  False     False  
2    False   True     False  
3    False  False     False  
4    False   True     False  
..     ...    ...       ...  
886  False   True     False  
887  False  False     False  
888  False   True     False  
889  False  False     False  
890  False   True     False  

[891 rows x 12 columns]

In [42]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [43]:
df.isna().any()

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [45]:
duplicates=df[df.duplicated()]
print(len(duplicates))

0


In [56]:
df1={"Movie":["Friends","Money Heist","Titanic","Incredibles", "Shrek"],
    "Year of Release":[1997, 2019, np.nan, 2005, np.nan],
    "Rating":[76, np.nan, 60, 36, 79],
    "Revenue(USD)":[np.nan, 40000,64000,np.nan, 73000,]}
df=pd.DataFrame(df1)
print("Movie List: \n", df)

Movie List: 
          Movie  Year of Release  Rating  Revenue(USD)
0      Friends           1997.0    76.0           NaN
1  Money Heist           2019.0     NaN       40000.0
2      Titanic              NaN    60.0       64000.0
3  Incredibles           2005.0    36.0           NaN
4        Shrek              NaN    79.0       73000.0


In [61]:
df["Revenue(USD)"]=df["Revenue(USD)"].fillna(df["Revenue(USD)"].median())
print("Movie List: \n", df)

Movie List: 
          Movie  Year of Release  Rating  Revenue(USD)
0      Friends           1997.0    76.0       66250.0
1  Money Heist           2019.0     NaN       40000.0
2      Titanic              NaN    60.0       64000.0
3  Incredibles           2005.0    36.0       68500.0
4        Shrek              NaN    79.0       73000.0


In [62]:
df["Rating"]=df["Rating"].interpolate()
print("Movielist: \n", df)

Movielist: 
          Movie  Year of Release  Rating  Revenue(USD)
0      Friends           1997.0    76.0       66250.0
1  Money Heist           2019.0    68.0       40000.0
2      Titanic              NaN    60.0       64000.0
3  Incredibles           2005.0    36.0       68500.0
4        Shrek              NaN    79.0       73000.0


In [63]:
df["Year of Release"]=df["Year of Release"].fillna(1999)
print("Movielist: \n", df)

Movielist: 
          Movie  Year of Release  Rating  Revenue(USD)
0      Friends           1997.0    76.0       66250.0
1  Money Heist           2019.0    68.0       40000.0
2      Titanic           1999.0    60.0       64000.0
3  Incredibles           2005.0    36.0       68500.0
4        Shrek           1999.0    79.0       73000.0


In [65]:
df["Year of Release"]=df["Year of Release"].astype(int)
print("Movie List: \n", df)

Movie List: 
          Movie  Year of Release  Rating  Revenue(USD)
0      Friends             1997    76.0       66250.0
1  Money Heist             2019    68.0       40000.0
2      Titanic             1999    60.0       64000.0
3  Incredibles             2005    36.0       68500.0
4        Shrek             1999    79.0       73000.0


In [49]:
#Creating the dataset
data= {
    "Name":["Alice", "Bob",np.nan, "Jay"],
    "Age":[23,35, 27,np.nan],
    "Score": [70,90,np.nan,86],
    }
df=pd.DataFrame(data)
print("Original Dataframe: \n" ,df)

Original Dataframe: 
     Name   Age  Score
0  Alice  23.0   70.0
1    Bob  35.0   90.0
2    NaN  27.0    NaN
3    Jay   NaN   86.0


In [51]:
df.describe()

Age      Score
count   3.000000   3.000000
mean   28.333333  82.000000
std     6.110101  10.583005
min    23.000000  70.000000
25%    25.000000  78.000000
50%    27.000000  86.000000
75%    31.000000  88.000000
max    35.000000  90.000000

In [53]:
df["Age"]=df["Age"].fillna(df["Age"].mean()) #filling missing column with mean
df["Score"]=df["Score"].interpolate() #filling the missing colum by interpolating
print("Dataset: \n", df)

Dataset: 
     Name        Age  Score
0  Alice  23.000000   70.0
1    Bob  35.000000   90.0
2    NaN  27.000000   88.0
3    Jay  28.333333   86.0


In [66]:
df=df.rename(columns={"Name":"Student_Name", "Score":"Exam_score"}) #renaming the columns Name and Score
print("Dataset: \n",df)

Dataset: 
          Movie  Year of Release  Rating  Revenue(USD)
0      Friends             1997    76.0       66250.0
1  Money Heist             2019    68.0       40000.0
2      Titanic             1999    60.0       64000.0
3  Incredibles             2005    36.0       68500.0
4        Shrek             1999    79.0       73000.0


In [67]:
#Creating the datasets
df1=pd.DataFrame({"ID":[1,2,3],
                 "Name":["Alice","Bob", "Mary"],
                 "Age":[23,30,27],})

df2=pd.DataFrame({"ID":[1,2,3],
                 "Score":[79,84,91]})
print("Name Data: \n", df1)
print("Score Data: \n", df2)

Name Data: 
    ID   Name  Age
0   1  Alice   23
1   2    Bob   30
2   3   Mary   27
Score Data: 
    ID  Score
0   1     79
1   2     84
2   3     91


In [68]:
merged=pd.merge(df1,df2, how="inner", on="ID") #merging dataset on the inner join
print("Merged Data: \n", merged)

Merged Data: 
    ID   Name  Age  Score
0   1  Alice   23     79
1   2    Bob   30     84
2   3   Mary   27     91


In [74]:
merged["Score_Percentage"]=(merged["Score"] / 100)*100 #adding a new column to the merged dataset
print("Dataset: \n", merged)

Dataset: 
    ID   Name  Age  Score  Score_Percentage
0   1  Alice   23     79              79.0
1   2    Bob   30     84              84.0
2   3   Mary   27     91              91.0
